const APP_LOAD = 'app/LOAD';
const FORMS_ADD = 'forms/ADD';
const FORMS_DELETE = 'forms/DELETE';
const FORMS_UPDATE = 'forms/UPDATE';
const QUESTIONS_ADD = 'questions/ADD';
const QUESTIONS_DELETE = 'questions/DELETE';
const QUESTIONS_UPDATE = 'questions/UPDATE';
const RESPONSES_ADD = 'responses/ADD';
const RESPONSES_DELETE = 'responses/DELETE';
const RESPONSES_UPDATE = 'responses/UPDATE';

export {
  APP_LOAD,
  FORMS_ADD,
  FORMS_DELETE,
  FORMS_UPDATE,
  QUESTIONS_ADD,
  QUESTIONS_DELETE,
  QUESTIONS_UPDATE,
  RESPONSES_ADD,
  RESPONSES_DELETE,
  RESPONSES_UPDATE,
}

export default {
  APP_LOAD,
  FORMS_ADD,
  FORMS_DELETE,
  FORMS_UPDATE,
  QUESTIONS_ADD,
  QUESTIONS_DELETE,
  QUESTIONS_UPDATE,
  RESPONSES_ADD,
  RESPONSES_DELETE,
  RESPONSES_UPDATE,
}
